-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(S.SALES_AMOUNT) * P.PRICE AS SALES
FROM OFFLINE_SALE S INNER JOIN PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC