-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(DATE_DIFF), 1) AS AVERAGE_DURATION
FROM (
    SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 AS DATE_DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS E
GROUP BY CAR_ID HAVING AVG(DATE_DIFF) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC