SELECT E.QUARTER, COUNT(*) AS ECOLI_COUNT
FROM (
    SELECT *, CASE
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') < '04-01' THEN '1Q'
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') < '07-01' THEN '2Q'
        WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%m-%d') < '10-01' THEN '3Q'
        ELSE '4Q'
    END AS QUARTER
    FROM ECOLI_DATA
) AS E
GROUP BY E.QUARTER
ORDER BY E.QUARTER