-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT *, RANK() OVER (
        PARTITION BY FISH_TYPE
        ORDER BY LENGTH DESC
    ) AS RNK
    FROM FISH_INFO
) T JOIN FISH_NAME_INFO N ON T.FISH_TYPE = N.FISH_TYPE 
WHERE RNK = 1
ORDER BY ID;