-- 코드를 입력하세요
# SELECT INGREDIENT_TYPE, TOTAL_ORDER
# FROM FIRST_HALF JOIN ICECREAM_INFO
# GROUP BY INGREDIENT_TYPE, TOTAL_ORDER
# ORDER BY TOTAL_ORDER ASC
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER)
FROM FIRST_HALF A JOIN ICECREAM_INFO B
    ON A.FLAVOR = B.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC